server:
  port: 8083

spring:
  application:
    name: assignment-service
  
  datasource:
    # Changed localhost to postgres
    url: jdbc:postgresql://postgres:5432/assignment_db
    username: sujaynimmagadda
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  rabbitmq:
    # Changed localhost to rabbitmq
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Changed localhost to auth-service
auth-service:
  url: http://auth-service:8081

# Assignment Configuration
assignment:
  auto-assign:
    enabled: false
    strategy: LEAST_LOADED
  max-tickets-per-agent: 10

# SLA Configuration
sla:
  business-hours:
    enabled: true
    start-time: "09:00"
    end-time: "18:00"
    timezone: "Asia/Kolkata"
  
  rules:
    CRITICAL:
      response-time-minutes: 5
      resolution-time-hours: 4
    HIGH:
      response-time-minutes: 60
      resolution-time-hours: 8
    MEDIUM:
      response-time-minutes: 240
      resolution-time-hours: 24
    LOW:
      response-time-minutes: 480
      resolution-time-hours: 48
  
  breach-check-interval: 60

# Feign Configuration
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      authServiceClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException
  
  retry:
    instances:
      authServiceClient:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  
  timelimiter:
    instances:
      authServiceClient:
        timeoutDuration: 5s

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.assignment: DEBUG
    org.springframework.amqp: DEBUG

# Switched to true to ensure proper Docker boot sequence
environment:
  SPRING_CLOUD_CONFIG_ENABLED: "true"
  SPRING_CLOUD_CONFIG_FAILFAST: "true"