server:
  port: 8081

spring:
  application:
    name: auth-service
  
  datasource:
    # Changed localhost to postgres
    url: jdbc:postgresql://postgres:5432/ticket_auth_db
    username: sujaynimmagadda
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  # In a real environment, move this to an environment variable in docker-compose
  secret: ${JWT_SECRET:your-super-secret-key-min-256-bits-change-this-in-production-environment}
  expiration: 86400000

logging:
  level:
    com.ticket: DEBUG
    org.springframework.web: DEBUG

# Switched to true so the service properly waits for the Config Server
environment:
  SPRING_CLOUD_CONFIG_ENABLED: "true"
  SPRING_CLOUD_CONFIG_FAILFAST: "true"