server:
  port: 8084

spring:
  application:
    name: notification-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: sujaynimmagadda
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: nsvsujay@gmail.com
    password: ahcwmyoztibtyjqh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Service URLs
services:
  ticket-service:
    url: http://localhost:8082
  auth-service:
    url: http://localhost:8081

auth-service:
  url: http://localhost:8081

# Feign Configuration
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      ticket-service:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: false
  compression:
    request:
      enabled: true
    response:
      enabled: true

# Notification Configuration
notification:
  email:
    enabled: true
    from: ${MAIL_USERNAME:noreply@ticketing.com}
    from-name: Ticket Management System
  
  retry:
    max-attempts: 3
    delay-seconds: 60

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      ticketServiceClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  
  retry:
    instances:
      ticketServiceClient:
        maxAttempts: 3
        waitDuration: 1s
  
  timelimiter:
    instances:
      ticketServiceClient:
        timeoutDuration: 5s

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

logging:
  level:
    com.notification: DEBUG
    com.notification.client: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.mail.javamail: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
    javax.mail: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/notification-service.log
    path: logs
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10

environment:
  SPRING_CLOUD_CONFIG_ENABLED: "false"
  SPRING_CLOUD_CONFIG_FAILFAST: "false"
