server:
  port: 8082

spring:
  application:
    name: ticket-service
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/ticket_service_db
      auto-index-creation: true
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# AWS S3 Configuration
aws:
  region: ap-south-1
  s3:
    bucket-name: ticket-attachements-2025
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}

# Service URLs
services:
  assignment-service:
    url: http://localhost:8083
  auth-service:
    url: http://localhost:8081

#Feign Configuration
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
      assignment-service:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: full

# RabbitMQ Exchanges and Queues
rabbitmq:
  exchange:
    name: ticket.exchange
  queue:
    ticket:
      name: ticket.queue
    notification:
      name: notification.queue
  routing-key:
    ticket-created: ticket.created
    ticket-assigned: ticket.assigned
    ticket-status-changed: ticket.status.changed
    ticket-updated: ticket.updated
    comment-added: comment.added

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      assignmentServiceClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      
      userServiceClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  
  retry:
    instances:
      assignmentServiceClient:
        maxAttempts: 3
        waitDuration: 1s
      
      userServiceClient:
        maxAttempts: 3
        waitDuration: 1s

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers

logging:
  level:
    com.ticket: DEBUG
    com.ticket.service.EventPublisherService: DEBUG
    com.ticket.client: DEBUG
    org.springframework.amqp: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.data.mongodb: INFO
    feign: DEBUG
  file:
    name: logs/ticket-service.log
    path: logs

environment:
  SPRING_CLOUD_CONFIG_ENABLED: "false"
  SPRING_CLOUD_CONFIG_FAILFAST: "false"
